[package]
name = "gdr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.21"
rmp-serde = "1.1.2"
serde = "1.0.197"
serde_json = "1.0.116"
