[package]
name = "bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
base64 = "0.21.7"
bincode = "1.3.3"
byteorder = "1.5.0"
chrono = "0.4.34"
dlhn = "0.1.6"
fasteval2 = { git = "https://github.com/zeozeozeo/fasteval2.git", branch = "sqrt-builtin", default-features = false, features = ["alpha-keywords"]}
hound = "3.5.1"
ijson = "0.1.3"
leb128 = "0.2.5"
log = "0.4.20"
lzma-rs = "0.3.0"
rand = "0.8.5"
rayon = "1.8.1"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
symphonia = { version = "0.5.3", features = ["all"] }
ybot_fmt = { path = "ybot_fmt" }
gdr = { path = "gdr" }
